#!/bin/bash
# each mutant against the test that is there to catch it: a FAIL is the proof
S=/tmp/claude-0/-home-user-jills-kitchen/63b8740a-97ce-5ff7-813a-d847b68fd153/scratchpad
cd /home/user/jills-kitchen
run(){ echo "-- mutant $1 -> $2"; JK_GAME_JS=$S/r2/mut/$1.js timeout 1500 python3 -u tests/run_tests.py -k $2 2>&1 | grep -E "^(PASS|FAIL|OPEN)|passed|^      " | grep -v "^      at " | cut -c1-300; }
run pass_one_box cooking_the_pass_opens_in_the_middle_and_keeps_its_row
run row_in_gap cooking_the_pass_opens_in_the_middle_and_keeps_its_row
run lamps_old cooking_the_pass_opens_in_the_middle_and_keeps_its_row
run fire_five_perfect cooking_on_fire_is_earned_by_a_run_of_fast_tables
run fire_no_once cooking_on_fire_is_earned_by_a_run_of_fast_tables
run fire_no_jill_bonus cooking_on_fire_is_earned_by_a_run_of_fast_tables
run fire_no_busy cooking_on_fire_is_earned_by_a_run_of_fast_tables
run no_walkback_pat jill_pats_a_cat_on_her_way_and_lets_go_for_work
run pat_ignores_work jill_pats_a_cat_on_her_way_and_lets_go_for_work
run pat_with_hands jill_pats_a_cat_on_her_way_and_lets_go_for_work
run staff_tab_day4 v24_round2_hiring_opens_after_day_one_and_pays
run full_fee v24_round2_hiring_opens_after_day_one_and_pays
run no_teach_rule v24_round2_hiring_opens_after_day_one_and_pays
run xq_dup v24_round2_xiuqin_once_in_every_save
run xq_no_add v24_round2_xiuqin_once_in_every_save
run reveal_old dylan_reveal_says_it_beside_him
run tap_queue_no_seat touch_controls
run legacy_crew_runs old_saves_load
run crew_dropped album_store_and_viewer_v181
run crew_dropped v24_saves_load_and_nothing_fires_on_load
run xq_dup v24_saves_load_and_nothing_fires_on_load
run rest_beat_announced every_player_save_migrates_plays_a_day_and_keeps_its_story
run reghead_card v24_rc7_2_a_regulars_head_at_a_busy_table_and_the_log_closes
run xq_not_working v24_xiuqin_is_there_from_day_one_and_is_not_free_labour
run xq_unpaid v24_xiuqin_is_there_from_day_one_and_is_not_free_labour
run xq_goes_home v24_xiuqin_stays_through_the_closing_like_the_staff
run xq_takes_place v24_xiuqin_is_never_hired_and_takes_no_place
run xq_takes_place v24_rc8_the_restaurants_three_lists_and_the_lounges_one
run yj_held_late v24_yijun_comes_early_in_a_fresh_game_and_meets_her_mother
run cap_l1_old v24_rc8_the_restaurants_three_lists_and_the_lounges_one
run cap_l1_old v24_restaurant_and_lounge_staff_are_two_pools_that_never_share_places
run cap_l1_old v24_an_old_shared_cap_save_keeps_everyone_and_waits
run news_day2_old v24_manual_tutorial_and_news_cover_the_new_content
run xq_scene_not_held v24_rc7_2_xiuqin_first_evening_holds_the_service
run start_1200 cooking_the_first_three_days_teach_three_kinds_of_work
run pass_one_box cooking_people_walk_round_the_counters
run teach_forever cooking_jill_and_the_cooks_hand_work_on
run teach_forever v24_round2_hiring_opens_after_day_one_and_pays
run jill_leaves_midstep cooking_one_jill_finishes_her_step_then_goes_and_nothing_of_hers_moves_on_while_she_is_away
run waiter_washes_with_guests workflow_waiters_keep_serving_and_one_at_most_washes
run one_wait_post qa_waiting_staff_do_not_stand_on_one_spot
run no_walkover jill_pats_a_cat_on_her_way_and_lets_go_for_work
run walkover_ignores_work jill_pats_a_cat_on_her_way_and_lets_go_for_work
run walkover_teleport jill_pats_a_cat_on_her_way_and_lets_go_for_work
echo "== done"
