"""Mutants of js/game.js for the round-2 tests: each is one of the problems a test is there to catch."""
import os
S='/tmp/claude-0/-home-user-jills-kitchen/63b8740a-97ce-5ff7-813a-d847b68fd153/scratchpad/r2/mut/'
src=open('/home/user/jills-kitchen/js/game.js',encoding='utf-8').read()
def mut(name,pairs):
    s=src
    for a,b in pairs:
        assert s.count(a)>=1,(name,a[:80]); s=s.replace(a,b,1)
    open(S+name+'.js','w',encoding='utf-8').write(s)
mut('pass_one_box',[("{bx0:P0,bx1:PASS_GAP.x0,by0:KY.passFeet+2,by1:KY.passTop+KY.passH+KY.passFace+2},{bx0:PASS_GAP.x1,bx1:P1,by0:KY.passFeet+2,by1:KY.passTop+KY.passH+KY.passFace+2},","{bx0:P0,bx1:P1,by0:KY.passFeet+2,by1:KY.passTop+KY.passH+KY.passFace+2},{bx0:P1,bx1:P1+1,by0:KY.passFeet+2,by1:KY.passTop+KY.passH+KY.passFace+2},")])
mut('row_in_gap',[("function wfRowX(i){const E=passEnds()","function wfRowX(i){return(projOn('pass')?64:80)+18+i*26;const E=passEnds()")])
mut('lamps_old',[("function passLamps(){return projOn('pass')?[110,170,230,290]:[112,156,244,288]}","function passLamps(){return projOn('pass')?[110,170,230,290]:[132,200,268]}")])
mut('fire_five_perfect',[("if(q==='P'){R.st.perfect++;R.streak++;if(!S.achievements.first)ach('first')}else R.streak=0;","if(q==='P'){R.st.perfect++;R.streak++;if(!S.achievements.first)ach('first');if(R.streak>=5&&R.fire<=0){R.streak=0;startFire()}}else R.streak=0;")])
mut('fire_no_once',[("if(R.frun>=FIRE_RUN&&!R.fireDone&&R.fire<=0)","if(R.frun>=FIRE_RUN&&R.fire<=0)")])
mut('fire_no_jill_bonus',[("R.frun=(R.frun||0)+(its.some(it=>it.byJill)?1.5:1);","R.frun=(R.frun||0)+1;")])
mut('fire_no_busy',[("if(ts.filter(t=>t.group).length<FIRE_BUSY*ts.length)return;","")])
mut('no_walkback_pat',[("&&(J.petCD||0)<R.t&&Math.random()<dt*3){const near=jillPatNear(J,30);","&&false&&(J.petCD||0)<R.t&&Math.random()<dt*3){const near=jillPatNear(J,30);")])
mut('pat_ignores_work',[("if(J.pet&&J.tx!=null){J.moving=false;J.pet.t-=dt;if(J.pet.t<=0)J.pet=null;else if(J.cur||J.q.length||jillWorkload()>2)J.pet=null;if(J.pet)return}","if(J.pet&&J.tx!=null){J.moving=false;J.pet.t-=dt;if(J.pet.t<=0)J.pet=null;if(J.pet)return}"),("if(!J.cur&&J.q.length){J.cur={t:J.q.shift()};planAct();J.idle=0}","if(!J.cur&&J.q.length&&!J.pet){J.cur={t:J.q.shift()};planAct();J.idle=0}")])
mut('pat_with_hands',[("&&J.tx===PASS.x&&J.ty===PASS.y&&!(J.hands||[]).length&&","&&J.tx===PASS.x&&J.ty===PASS.y&&")])
mut('staff_tab_day4',[("{k:'staff',n:'員工',from:1}","{k:'staff',n:'員工',from:4}")])
mut('full_fee',[("Math.round(R0.hire*(S.level<=1&&!R0.lounge?.5:1))","Math.round(R0.hire)")])
mut('no_teach_rule',[("function wfJillTeach(n){if(S.day>3)return false;","function wfJillTeach(n){return false;if(S.day>3)return false;")])
mut('xq_dup',[("let m=o.crew.find(is);if(!m){","let m=null;if(!m){")])
mut('xq_no_add',[("let m=o.crew.find(is);if(!m){const f=","let m=o.crew.find(is);if(!m)return o;if(!m){const f=")])
mut('reveal_old',[(" if(D.waitJ&&st===2&&D.state!=='reveal'){D.moving=false;if(J.walking||J.after==='atHim'||J.act==='standing')return;D.waitJ=0}",""),("  if(Math.hypot(L.x-D.x,L.y-D.y)>REVEAL_NEAR&&(L.himTries||0)<4){","  if(false){"),("  if(Math.hypot(L.x-D.x,L.y-D.y)>REVEAL_NEAR){D.waitJ=0;L.act='toSofa';return}","")])
mut('tap_queue_no_seat',[("const g=frontQueueAt(p);if(g){const t=freeTableFor(g);if(t){seatGroup(g,t);","const g=frontQueueAt(p);if(g){const t=freeTableFor(g);if(false){seatGroup(g,t);")])
mut('legacy_crew_runs',[("function legacyCrew(o){if(!o.crewMig){","function legacyCrew(o){if(true){")])
mut('crew_dropped',[("o.crew=Array.isArray(o.crew)?o.crew:[];const is=","o.crew=[];const is=")])
mut('rest_beat_announced',[("if(ls&&Array.isArray(ls._rest)&&!ls._rest.includes(XQ_REST_BEAT))ls._rest.push(XQ_REST_BEAT)","")])
mut('reghead_card',[("const rg=hitRegular(p);if(rg&&!paused){const wt=regTableWork(rg);if(wt){","const rg=hitRegular(p);if(rg&&!paused){const wt=regTableWork(rg);if(false){")])
mut('xq_not_working',[("function crewUpd(dt){R.cw=R.cw||{};for(const m of S.crew||[]){","function crewUpd(dt){R.cw=R.cw||{};for(const m of S.crew||[]){if(m.core)continue;")])
mut('xq_unpaid',[("function crewWages(){return(S.crew||[]).reduce((a,m)=>a+crewWage(m),0)}","function crewWages(){return(S.crew||[]).reduce((a,m)=>a+(m.core?0:crewWage(m)),0)}")])
mut('xq_goes_home',[("function crewHere(m){const e=crewAwayOf(m);","function crewHere(m){if(m.core&&R&&R.closing!=null&&R.closing>12)return false;const e=crewAwayOf(m);")])
mut('xq_takes_place',[("function roleCrew(r){return poolCrew('restaurant').filter(m=>m.role===r&&!m.core)}","function roleCrew(r){return poolCrew('restaurant').filter(m=>m.role===r)}")])
mut('yj_held_late',[("Y=(p,g,k)=>out.push(Object.assign({name:YJN,p,type:'regular',size:1,grp:g,k},xqHelperMode()?{t:.9,o:{hold:1}}:{}))","Y=(p,g,k)=>out.push(Object.assign({name:YJN,p,type:'regular',size:1,grp:g,k},{t:.9,o:{hold:1}}))")])
mut('cap_l1_old',[("const CAP_LEVEL=[{chef:1,waiter:1,cleaner:0},","const CAP_LEVEL=[{chef:1,waiter:0,cleaner:0},")])
mut('news_day2_old',[("現在可以請員工了：第 1 級可以請一位<b>廚師</b>","第 1 級可以請一位<b>廚師</b>")])
mut('xq_scene_not_held',[("const m=xqHere();if(!m)return;factSet('xq_helper');\n v24Scene([","const m=xqHere();if(!m)return;factSet('xq_helper');\n scene([")])
mut('start_1200',[("const START_MONEY=2000;","const START_MONEY=1200;")])
mut('teach_forever',[("return !!d&&baseOf(n.d)===d&&!(S.jillMade||{})[d]}","return !!d&&baseOf(n.d)===d}")])
mut('jill_leaves_midstep',[("if(jt&&J.kcur===jt.id)return true;   /* a step at a station under way */","")])
mut('waiter_washes_with_guests',[("if(crewPool(m)!=='lounge'&&ddWashNow(m)&&passLoad()<.5&&!ddWaiterHasGuests(m)&&","if(crewPool(m)!=='lounge'&&ddWashNow(m)&&")])
mut('one_wait_post',[("function waitPost(m){const k=Math.max(0,(S.crew||[]).filter(x=>x.role==='waiter').indexOf(m));return WAIT_POSTS[k%WAIT_POSTS.length]}","function waitPost(m){return WAIT_POSTS[0]}")])
mut('no_walkover',[("if(!J.petGo&&!J.visit&&!J.rest&&!J.pet&&!(J.hands||[]).length&&J.idle>1.2&&J.calm>2.5&&","if(false&&!J.petGo&&!J.visit&&!J.rest&&!J.pet&&!(J.hands||[]).length&&J.idle>1.2&&J.calm>2.5&&")])
mut('walkover_ignores_work',[(" if(J.petGo&&(J.cur||J.q.length||J.rest||J.visit||jillWorkload()>1||R.closing!=null)){J.petGo=null;if(!J.cur&&!J.rest&&!J.visit){J.tx=null;J.ty=null;J.moving=false}}",""),("if(!J.cur&&J.q.length){J.cur={t:J.q.shift()};planAct();J.idle=0}","if(!J.cur&&J.q.length&&!J.petGo){J.cur={t:J.q.shift()};planAct();J.idle=0}")])
mut('walkover_teleport',[("J.petGo={cat:c};J.troom='main';J.tx=clamp(c.x+(c.x<=J.x?16:-16),20,380);J.ty=c.y+4;return}","J.petGo={cat:c};J.troom='main';J.x=J.tx=clamp(c.x+(c.x<=J.x?16:-16),20,380);J.y=J.ty=c.y+4;return}")])
mut('pat_on_any_walk',[("if(J.tx!=null&&!J.cur&&!J.pet&&!J.visit&&!J.fp&&!J.rest&&R.closing==null&&J.troom==='main'&&(J.room||'main')==='main'&&J.tx===PASS.x&&J.ty===PASS.y&&!(J.hands||[]).length&&","if(J.tx!=null&&!J.pet&&!J.visit&&!J.fp&&!J.rest&&R.closing==null&&(J.room||'main')==='main'&&")])
print('ok')
