"""Story Photo art: crops of the approved concept sheets (docs/v23/story_photos_*.png), by stable key, packed as
js/story_art.js (window.STORY_ART). Panels are cut inside their frames so no sheet caption ends up in the picture;
the album carries the title. 720x540 WebP (the album shows 360x270)."""
import base64, io, os, sys
from PIL import Image
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SM = os.path.join(ROOT, 'docs/v23/story_photos_sophie_mia_concept.png')
KD = os.path.join(ROOT, 'docs/v23/story_photos_qing_tuo_ken_du_concept.png')
VAL = os.path.join(ROOT, 'docs/v23/story_photo_jill_dylan_valentine.png')   # 2026-10-01, supplied by the player: Dylan × Jill, Valentine's
WANG = os.path.join(ROOT, 'docs/v23/story_photo_wang_anniv.jpg')             # 2026-10-01, supplied by the player: 王先生 × 王太太, the anniversary
MEAL = os.path.join(ROOT, 'docs/v23/story_photo_staff_meal.png')             # 2026-10-01, supplied by the player (second version, made to the spec): the staff meal
# key -> (sheet, box). Boxes chosen by eye on the sheets; 4:3 is enforced by a centered crop of the box.
ART = {
    'sophie_mia_leave':  (SM, (1200, 424, 1536, 690)),   # 《一起回家》 panel, right of its caption
    'sophie_mia_arrive': (SM, (430, 0, 1010, 412)),      # the top banner's two faces, right of the title text
    'ken_du':            (KD, (645, 682, 930, 890)),     # 《乾一杯，繼續吵》
    'ken_du_seat':       (KD, (645, 936, 930, 1165)),    # 《固定的位置》
    'qing_tuo':          (KD, (22, 682, 306, 890)),      # 《一起收工》 — the small plate
    'qing_tuo_late':     (KD, (325, 936, 610, 1165)),    # 《有你在的晚班》
    'jill_dylan_valentine': (VAL, (150, 0, 1515, 1024)), # 《情人節，還在追》 — both of them, the cake, the cat asleep on the counter
    'wang_anniv':        (WANG, (0, 70, 1093, 890)),     # 《今年也在這裡》 — the gift, both faces, the anniversary box
    'staff_meal':        (MEAL, (120, 0, 1485, 1024)),   # 《開店前》 — the player's second version (to spec): the whole crew, the two cats, the room; every face kept whole
}
def crop43(im, box):
    x0, y0, x1, y1 = box; w, h = x1 - x0, y1 - y0
    if w / h > 4 / 3: nw = int(h * 4 / 3); x0 += (w - nw) // 2; x1 = x0 + nw
    else: nh = int(w * 3 / 4); y0 += (h - nh) // 2; y1 = y0 + nh
    return im.crop((x0, y0, x1, y1)).resize((720, 540), Image.LANCZOS)
def main():
    out = {}
    for k, (sheet, box) in ART.items():
        im = Image.open(sheet).convert('RGB'); c = crop43(im, box)
        buf = io.BytesIO(); c.save(buf, 'WEBP', quality=82, method=6)
        out[k] = 'data:image/webp;base64,' + base64.b64encode(buf.getvalue()).decode()
        if '--png' in sys.argv:
            os.makedirs(os.path.join(ROOT, 'docs/evidence/v23/story_art'), exist_ok=True)
            c.save(os.path.join(ROOT, 'docs/evidence/v23/story_art', k + '.png'))
    js = '/* generated by tools/story_art.py — Story Photo art cut from the approved concept sheets, by stable key */\nwindow.STORY_ART=' + __import__('json').dumps(out, ensure_ascii=False) + ';\n'
    open(os.path.join(ROOT, 'js/story_art.js'), 'w', encoding='utf-8').write(js)
    print('story_art.js', len(js) // 1024, 'KB,', len(out), 'pictures')
if __name__ == '__main__': main()
